---

- name: "Installation pré-requis"
  ansible.builtin.apt:
    name: python3-setuptools,python3-pip,python3-dev,python3-wheel,python3-pyqt5,python3-pyqt5.qtsvg,python3-pyqt5.qtwebsockets
    state: present

- name: "Installation"
  command: pip3 install gns3-server

