---

- name: "Création répertoire"
  ansible.builtin.file:
    path: "{{ datadir_docker }}"
    state: directory
    mode: 0711

- name: "Redémarrage service"
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    masked: no
    state: restarted

