---

- name: "Activation routage IP"
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/ip_forward.conf
    reload: yes

- name: "Démarrage réseau par défaut"
  ansible.builtin.command: virsh net-start default

- name: "Démarrage automatique réseau par défaut"
  ansible.builtin.command: virsh net-autostart default


