---

- name: "Prise en charge paquets 32 bits"
  ansible.builtin.command: dpkg --add-architecture i386
  args:
    creates: /var/lib/dpkg/arch

- name: "Installation librairie"
  ansible.builtin.apt:
    update_cache: yes
    name: libssl1.1:i386
    state: present

- name: "Ajout lien librairie"
  ansible.builtin.file:
    src: libcrypto.so.1.1
    dest: /usr/lib/i386-linux-gnu/libcrypto.so.4
    state: link

